In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("parkinsons.data")

In [3]:
data

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [5]:
data.drop(['name'],axis =1,inplace=True)

In [6]:
data.shape

(195, 23)

In [7]:
X = data.drop(['status'],axis=1)
Y = data['status']

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection  import train_test_split,RandomizedSearchCV,GridSearchCV
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=10,shuffle=True)

X_train.shape,Y_test.shape

((156, 22), (39,))

In [9]:
parkinsons_scaler =  StandardScaler()
X_train = parkinsons_scaler.fit_transform(X_train)
X_test = parkinsons_scaler.transform(X_test)
X_train

array([[ 0.49306206,  0.39830971, -0.99389319, ..., -0.83944482,
         0.68988517, -0.86238115],
       [ 0.58299747,  2.52251992, -0.80459257, ...,  1.91539224,
         1.03075666,  0.44509943],
       [ 0.67633328, -0.05028816, -0.87460654, ..., -1.02717294,
        -0.56768879,  0.04914955],
       ...,
       [-0.84066737, -0.65281401, -0.41053275, ...,  0.19332405,
        -0.96769138, -0.46165777],
       [ 2.2638171 ,  0.62961537,  2.84180583, ..., -1.20124448,
        -0.02577355, -1.23634469],
       [-0.02799827, -0.37952038, -1.20094075, ...,  0.38308363,
         0.83900789,  1.67836795]], shape=(156, 22))

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,f1_score

In [11]:
def evaluate_model(y_true, y_pred):
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "recall": recall_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred)
    }


In [12]:
models ={
    'LogisticRegression':LogisticRegression(),
    "Xgboost":XGBClassifier(verbose=0),
    "DecisionTree":DecisionTreeClassifier(),
    "Adaboost" : AdaBoostClassifier(),
    "RandomForest" : RandomForestClassifier(),
    "KNeighbors" : KNeighborsClassifier()
}
models_list = []
score_test_list = []
score_train_list = []

for i in range(len(models)):
    model = list(models.values())[i]

    model.fit(X_train,Y_train)
    Y_train_pred = model.predict(X_train)
    Y_test_pred = model.predict(X_test)
    train_metrics = evaluate_model(Y_train,Y_train_pred)
    test_metrics = evaluate_model(Y_test,Y_test_pred)


    models_list.append(list(models.keys())[i])
    print(list(models.keys())[i])
    print("Model Performance For Training Set")
    print("accuracy_score:",train_metrics['accuracy'])
    print("recall_score:",train_metrics['recall'])
    print("precision_score:",train_metrics['precision'])
    print("f1_score:",train_metrics['f1'])

    print(confusion_matrix(Y_train,Y_train_pred))
    score_train_list.append(train_metrics['accuracy'])




    print(list(models.keys())[i])
    print("Model Performance For test Set")
    print("accuracy_score:",test_metrics['accuracy'])
    print("recall_score:",test_metrics['recall'])
    print("precision_score:",test_metrics['precision'])
    print("f1_score:",test_metrics['f1'])
    print(confusion_matrix(Y_test,Y_test_pred))
    print('==' * 50)
    score_test_list.append(test_metrics['accuracy'])




LogisticRegression
Model Performance For Training Set
accuracy_score: 0.8717948717948718
recall_score: 0.9491525423728814
precision_score: 0.8888888888888888
f1_score: 0.9180327868852459
[[ 24  14]
 [  6 112]]
LogisticRegression
Model Performance For test Set
accuracy_score: 0.8205128205128205
recall_score: 0.8620689655172413
precision_score: 0.8928571428571429
f1_score: 0.8771929824561403
[[ 7  3]
 [ 4 25]]
Xgboost
Model Performance For Training Set
accuracy_score: 1.0
recall_score: 1.0
precision_score: 1.0
f1_score: 1.0
[[ 38   0]
 [  0 118]]
Xgboost
Model Performance For test Set
accuracy_score: 0.9230769230769231
recall_score: 0.9655172413793104
precision_score: 0.9333333333333333
f1_score: 0.9491525423728814
[[ 8  2]
 [ 1 28]]
DecisionTree
Model Performance For Training Set
accuracy_score: 1.0
recall_score: 1.0
precision_score: 1.0
f1_score: 1.0
[[ 38   0]
 [  0 118]]
DecisionTree
Model Performance For test Set
accuracy_score: 0.9230769230769231
recall_score: 0.9655172413793104
pr

c:\projects\MultiDiseaseClassification\DisClf\Lib\site-packages\xgboost\training.py:183: UserWarning: [01:07:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "verbose" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Adaboost
Model Performance For Training Set
accuracy_score: 1.0
recall_score: 1.0
precision_score: 1.0
f1_score: 1.0
[[ 38   0]
 [  0 118]]
Adaboost
Model Performance For test Set
accuracy_score: 0.8974358974358975
recall_score: 0.9310344827586207
precision_score: 0.9310344827586207
f1_score: 0.9310344827586207
[[ 8  2]
 [ 2 27]]
RandomForest
Model Performance For Training Set
accuracy_score: 1.0
recall_score: 1.0
precision_score: 1.0
f1_score: 1.0
[[ 38   0]
 [  0 118]]
RandomForest
Model Performance For test Set
accuracy_score: 0.9230769230769231
recall_score: 0.9655172413793104
precision_score: 0.9333333333333333
f1_score: 0.9491525423728814
[[ 8  2]
 [ 1 28]]
KNeighbors
Model Performance For Training Set
accuracy_score: 0.9423076923076923
recall_score: 0.9745762711864406
precision_score: 0.9504132231404959
f1_score: 0.9623430962343096
[[ 32   6]
 [  3 115]]
KNeighbors
Model Performance For test Set
accuracy_score: 0.8974358974358975
recall_score: 0.9310344827586207
precision_score:

In [13]:
param_grid = {
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.01, 0.1, 1, 10],
            'solver': ['liblinear', 'lbfgs']
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1]
        }
    },
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [100, 200],
            'max_depth': [None, 10, 20],
            'min_samples_split': [2, 5]
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7, 9],
            'weights': ['uniform', 'distance'],
            'metric': ['euclidean', 'manhattan']
        }
    },
    'XGBoost': {
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss', verbosity=0),
        'params': {
            'n_estimators': [50, 100],
            'max_depth': [3, 5, 7],
            'learning_rate': [0.01, 0.1, 0.2]
        }
    }
}

best_models = {}
best_score = []


for name,mp in param_grid.items():
    print(f"tuning {name}")
    grid = GridSearchCV(estimator=mp['model'],param_grid=mp['params'],cv=5,n_jobs=-1,scoring='accuracy')
    grid.fit(X_train,Y_train)
    print(f"Best params for {name}: {grid.best_params_}")
    print(f"Best cross-validation accuracy: {grid.best_score_:.4f}")
    best_score.append(grid.best_score_)
    print("="*60)
    best_models[name] = grid.best_estimator_


for name, model in best_models.items():
    y_pred = model.predict(X_test)
    print(f"Evaluation for {name}:")
    metrics = evaluate_model(Y_test, y_pred)
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")
    print("-" * 40)



tuning LogisticRegression
Best params for LogisticRegression: {'C': 10, 'solver': 'lbfgs'}
Best cross-validation accuracy: 0.8520
tuning AdaBoost
Best params for AdaBoost: {'learning_rate': 1, 'n_estimators': 150}
Best cross-validation accuracy: 0.9357
tuning RandomForest
Best params for RandomForest: {'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 100}
Best cross-validation accuracy: 0.9163
tuning KNeighbors
Best params for KNeighbors: {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'}
Best cross-validation accuracy: 0.9292
tuning XGBoost
Best params for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}
Best cross-validation accuracy: 0.9228
Evaluation for LogisticRegression:
accuracy: 0.8205
recall: 0.8276
precision: 0.9231
f1: 0.8727
----------------------------------------
Evaluation for AdaBoost:
accuracy: 0.8718
recall: 0.8966
precision: 0.9286
f1: 0.9123
----------------------------------------
Evaluation for RandomForest:
accuracy: 0.89

In [14]:
max(best_score)

np.float64(0.9356854838709678)

In [15]:
best_models

{'LogisticRegression': LogisticRegression(C=10, max_iter=1000),
 'AdaBoost': AdaBoostClassifier(learning_rate=1, n_estimators=150),
 'RandomForest': RandomForestClassifier(max_depth=10, min_samples_split=5),
 'KNeighbors': KNeighborsClassifier(metric='euclidean', n_neighbors=7, weights='distance'),
 'XGBoost': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric='logloss',
               feature_types=None, feature_weights=None, gamma=None,
               grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=0.1, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=3, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
             

In [16]:
parkinsons_model = AdaBoostClassifier(learning_rate=1, n_estimators=150)
parkinsons_model.fit(X_train,Y_train)
Y_test_pred =parkinsons_model.predict(X_test)

Y_test_pred

array([1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [17]:
import pickle,os
os.makedirs("models", exist_ok=True)

with open("models/parkinsons_model.pkl", 'wb') as file:
    pickle.dump(parkinsons_model, file)

with open("models/parkinsons_scaler.pkl", 'wb') as file:
    pickle.dump(parkinsons_scaler, file)